name: '✨ Улучшения в проекте'
description: Предложить новую возможность для библиотеки или её инструментов.
title: '[Feature]: '
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Проблема / мотивация
      description: Чего не хватает сейчас или что неудобно? Чего вы пытаетесь добиться?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Предлагаемое решение
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Рассмотренные альтернативы

  - type: textarea
    id: context
    attributes:
      label: Дополнительный контекст
      description: Ссылки, аналогичные решения, связанные issue и т.п.
