// Namespace imports, not named (`import { readFileSync } from 'node:fs'`):
// bundlers building for the browser (Vite/Rollup) externalize Node builtins
// to a stub module, and a *named* import is statically bound against that
// stub's exports at bundle time - even for code a later tree-shaking pass
// would otherwise drop as unreachable - which hard-fails the build. A
// namespace import only resolves `nodeFs.readFileSync` at the property-access
// site, so it tree-shakes away cleanly once nothing in this module is
// actually reachable from the app's imports (see `defaultDataDir` below).
import * as nodeCrypto from 'node:crypto';
import * as nodeFs from 'node:fs';
import path from 'node:path';
import * as nodeUrl from 'node:url';
import {
  assertDatasetVersion,
  DatasetIntegrityError,
  type Dataset,
  type DatasetMeta,
  type OperatorsIndex,
  type TableName,
} from './types.js';

// Computed lazily (inside a function, not at module top level) so it's only
// ever evaluated - and only ever needs `node:url` to actually resolve - when
// `loadDataset`/`createRuPhoneBase` are reachable from the app's imports. A
// browser app that imports only `createRuPhoneBaseFromData` never reaches
// this function, so a bundler's tree-shaking drops it (and the rest of this
// file's `fs`-touching code) entirely instead of shipping dead Node-only
// code - or a broken `node:*` import - to the browser.
function defaultDataDir(): string {
  const __dirname = path.dirname(nodeUrl.fileURLToPath(import.meta.url));
  return path.join(__dirname, 'data');
}

const ALL_TABLES: TableName[] = ['fixed', 'mobile'];

export interface LoadDatasetOptions {
  /** Directory to load the compiled JSON from. Defaults to the dataset bundled with this package. */
  dataDir?: string;
  /**
   * Which of the lookup tables to load - defaults to both. Pass a narrower
   * list to skip reading/parsing tables you don't need, e.g. `['mobile']` to
   * avoid loading `fixed.json` (by far the largest file) when only
   * mobile-number lookups are required.
   */
  include?: TableName[];
}

export function sha256Hex(content: Buffer | string): string {
  return nodeCrypto.createHash('sha256').update(content).digest('hex');
}

/**
 * Verifies SHA-256 digests of the given on-disk dataset files against `meta.files`.
 * Throws `DatasetIntegrityError` when the manifest is missing, a hash is absent, or a digest mismatches.
 */
export function assertDatasetFileHashes(meta: DatasetMeta, files: { file: string; content: Buffer | string }[]): void {
  if (!Array.isArray(meta.files) || meta.files.length === 0) {
    throw new DatasetIntegrityError('missing-manifest');
  }
  const byName = new Map(meta.files.map((f) => [f.file, f.sha256]));
  for (const { file, content } of files) {
    const expected = byName.get(file);
    if (typeof expected !== 'string' || expected.length === 0) {
      throw new DatasetIntegrityError('missing-hash', file);
    }
    const actual = sha256Hex(content);
    if (actual !== expected) {
      throw new DatasetIntegrityError('mismatch', file, expected, actual);
    }
  }
}

/** Picks which operators index file to load for the requested tables. */
export function operatorsFileForInclude(include: TableName[]): string {
  const wantFixed = include.includes('fixed');
  const wantMobile = include.includes('mobile');
  if (wantFixed && wantMobile) return 'operators.json';
  if (wantFixed) return 'operators-fixed.json';
  if (wantMobile) return 'operators-mobile.json';
  return 'operators.json';
}

/**
 * Loads the compiled dataset from a directory (fixed/mobile/regions/
 * operators/timezones/meta .json). Defaults to the dataset bundled with this
 * package; pass `dataDir` to load a dataset regenerated by the
 * `ru-phone-base-build` CLI instead (e.g. from a fresher raw-data snapshot),
 * without needing to reinstall/republish this package.
 *
 * Throws `DatasetVersionError` if `meta.version` is missing or does not match
 * this library's `DATASET_VERSION`. Throws `DatasetIntegrityError` if any
 * loaded data file's SHA-256 does not match `meta.files`.
 */
export function loadDataset(options: LoadDatasetOptions = {}): Dataset {
  const { dataDir = defaultDataDir(), include = ALL_TABLES } = options;
  const meta = JSON.parse(nodeFs.readFileSync(path.join(dataDir, 'meta.json'), 'utf-8')) as Dataset['meta'];
  assertDatasetVersion(meta);

  const operatorsFile = operatorsFileForInclude(include);
  const names = [
    ...(include.includes('fixed') ? (['fixed.json'] as const) : []),
    ...(include.includes('mobile') ? (['mobile.json'] as const) : []),
    'regions.json',
    operatorsFile,
    'timezones.json',
  ] as const;

  const buffers = Object.fromEntries(
    names.map((name) => [name, nodeFs.readFileSync(path.join(dataDir, name))]),
  ) as Record<string, Buffer>;
  assertDatasetFileHashes(
    meta,
    names.map((file) => ({ file, content: buffers[file] })),
  );

  const parse = <T>(name: string): T => JSON.parse(buffers[name].toString('utf-8')) as T;
  return {
    ...(include.includes('fixed') ? { fixed: parse('fixed.json') } : {}),
    ...(include.includes('mobile') ? { mobile: parse('mobile.json') } : {}),
    regions: parse('regions.json'),
    operators: parse<OperatorsIndex>(operatorsFile),
    timezones: parse('timezones.json'),
    meta,
  };
}
