import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  assertDatasetVersion,
  DatasetIntegrityError,
  type Dataset,
  type DatasetMeta,
  type TableName,
} from './types.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DEFAULT_DATA_DIR = path.join(__dirname, 'data');

const ALL_TABLES: TableName[] = ['fixed', 'mobile'];

export interface LoadDatasetOptions {
  /** Directory to load the compiled JSON from. Defaults to the dataset bundled with this package. */
  dataDir?: string;
  /**
   * Which of the lookup tables to load - defaults to both. Pass a narrower
   * list to skip reading/parsing tables you don't need, e.g. `['mobile']` to
   * avoid loading `fixed.json` (by far the largest file) when only
   * mobile-number lookups are required.
   */
  include?: TableName[];
}

export function sha256Hex(content: Buffer | string): string {
  return createHash('sha256').update(content).digest('hex');
}

/**
 * Verifies SHA-256 digests of the given on-disk dataset files against `meta.files`.
 * Throws `DatasetIntegrityError` when the manifest is missing, a hash is absent, or a digest mismatches.
 */
export function assertDatasetFileHashes(meta: DatasetMeta, files: { file: string; content: Buffer | string }[]): void {
  if (!Array.isArray(meta.files) || meta.files.length === 0) {
    throw new DatasetIntegrityError('missing-manifest');
  }
  const byName = new Map(meta.files.map((f) => [f.file, f.sha256]));
  for (const { file, content } of files) {
    const expected = byName.get(file);
    if (typeof expected !== 'string' || expected.length === 0) {
      throw new DatasetIntegrityError('missing-hash', file);
    }
    const actual = sha256Hex(content);
    if (actual !== expected) {
      throw new DatasetIntegrityError('mismatch', file, expected, actual);
    }
  }
}

/**
 * Loads the compiled dataset from a directory (fixed/mobile/regions/
 * operators/timezones/meta .json). Defaults to the dataset bundled with this
 * package; pass `dataDir` to load a dataset regenerated by the
 * `ru-phone-base-build` CLI instead (e.g. from a fresher raw-data snapshot),
 * without needing to reinstall/republish this package.
 *
 * Throws `DatasetVersionError` if `meta.version` is missing or does not match
 * this library's `DATASET_VERSION`. Throws `DatasetIntegrityError` if any
 * loaded data file's SHA-256 does not match `meta.files`.
 */
export function loadDataset(options: LoadDatasetOptions = {}): Dataset {
  const { dataDir = DEFAULT_DATA_DIR, include = ALL_TABLES } = options;
  const meta = JSON.parse(readFileSync(path.join(dataDir, 'meta.json'), 'utf-8')) as Dataset['meta'];
  assertDatasetVersion(meta);

  const names = [
    ...(include.includes('fixed') ? (['fixed.json'] as const) : []),
    ...(include.includes('mobile') ? (['mobile.json'] as const) : []),
    'regions.json',
    'operators.json',
    'timezones.json',
  ] as const;

  const buffers = Object.fromEntries(names.map((name) => [name, readFileSync(path.join(dataDir, name))])) as Record<
    (typeof names)[number],
    Buffer
  >;
  assertDatasetFileHashes(
    meta,
    names.map((file) => ({ file, content: buffers[file] })),
  );

  const parse = <T>(name: (typeof names)[number]): T => JSON.parse(buffers[name].toString('utf-8')) as T;
  return {
    ...(include.includes('fixed') ? { fixed: parse('fixed.json') } : {}),
    ...(include.includes('mobile') ? { mobile: parse('mobile.json') } : {}),
    regions: parse('regions.json'),
    operators: parse('operators.json'),
    timezones: parse('timezones.json'),
    meta,
  };
}
