import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Dataset, TableName } from './types.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DEFAULT_DATA_DIR = path.join(__dirname, 'data');

const ALL_TABLES: TableName[] = ['fixed', 'mobile'];

export interface LoadDatasetOptions {
  /** Directory to load the compiled JSON from. Defaults to the dataset bundled with this package. */
  dataDir?: string;
  /**
   * Which of the lookup tables to load - defaults to both. Pass a narrower
   * list to skip reading/parsing tables you don't need, e.g. `['mobile']` to
   * avoid loading `fixed.json` (by far the largest file) when only
   * mobile-number lookups are required.
   */
  include?: TableName[];
}

/**
 * Loads the compiled dataset from a directory (fixed/mobile/regions/
 * timezones/meta .json). Defaults to the dataset bundled with this package;
 * pass `dataDir` to load a dataset regenerated by the `ru-phone-base-build`
 * CLI instead (e.g. from a fresher raw-data snapshot), without needing to
 * reinstall/republish this package.
 */
export function loadDataset(options: LoadDatasetOptions = {}): Dataset {
  const { dataDir = DEFAULT_DATA_DIR, include = ALL_TABLES } = options;
  const read = <T>(name: string): T => JSON.parse(readFileSync(path.join(dataDir, name), 'utf-8')) as T;
  return {
    ...(include.includes('fixed') ? { fixed: read('fixed.json') } : {}),
    ...(include.includes('mobile') ? { mobile: read('mobile.json') } : {}),
    regions: read('regions.json'),
    timezones: read('timezones.json'),
    meta: read('meta.json'),
  };
}
